# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express.
apiVersion: v1
kind: Secret
metadata:
   name: secret
type: Opaque
data:
  username: cGFzc3dvcmQ=  #username
  password: dXNlcm5hbWU=   #passowrd
    
